steps:
  # Build Docker image for Laravel API with MySQL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/strayeye/waterfall-apps/api:mysql-${BUILD_ID}'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/strayeye/waterfall-apps/api:mysql-${BUILD_ID}']

  # Deploy to Cloud Run with MySQL environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'waterfall-api'
      - '--image=asia-southeast1-docker.pkg.dev/strayeye/waterfall-apps/api:mysql-${BUILD_ID}'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=600'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--add-cloudsql-instances=strayeye:asia-southeast1:waterfall-mysql'
      # Set non-sensitive environment variables.
      # --- FINAL FIX: Using DB_SOCKET for the Cloud SQL connection path. Removed incorrect DB_HOST.
      - '--set-env-vars=APP_ENV=production,APP_DEBUG=false,APP_NAME=Waterfall Party API,LOG_CHANNEL=stderr,LOG_LEVEL=info,CORS_ALLOWED_ORIGINS=https://phangan.ai,DB_CONNECTION=mysql,DB_DATABASE=waterfall_tickets,DB_SOCKET=/cloudsql/strayeye:asia-southeast1:waterfall-mysql,OMISE_PUBLIC_KEY=pkey_test_64v08ahvxzavuuecnaz,APP_KEY=base64:KymzNV4WA3Uhd3EEz5MmSrnHpGXFDRA/N1p33HcdNyk='
      # Mount sensitive values from Secret Manager.
      - '--set-secrets=DB_USERNAME=waterfall-db-username:latest,DB_PASSWORD=waterfall-db-password:latest,OMISE_SECRET_KEY=omise-secret-key:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/strayeye/waterfall-apps/api:mysql-${BUILD_ID}'

timeout: 1200s
