version: '3.8'

services:
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000

  api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-api:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=waterfall_tickets
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=waterfall_tickets
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: